name: Build project

on: [push, pull_request]

jobs:
  buildForWebGL:
    name: Build for web gl
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: false
          
      - uses: actions/cache@v2
        with:
          path: AsteroidsClone/Library
          key: Library-WebGL
          restore-keys: Library-
          
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL 
          projectPath: AsteroidsClone
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build-WebGL
          path: build/WebGL
          
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh_pages
          FOLDER: build/WebGL/WebGL/.

